### PR TITLE
Update hpcloud/tail and fsnotify

### LINKED ISSUE #5: tail rotated log files
Hello!
Does stream_exporter tail mode supports file rotation?
I tried to attach log directory and made tail to one of them.
Then file was rotated, after that tail filter did not reacted on trigger words not in new log file nor in rotated.

### PR DESCRIPTION
**Pull request by carlpett**
Fixes #5 

This depends on a manual merge of [fsnotify #205](https://github.com/fsnotify/fsnotify/pull/205) in the vendor directory, which is pretty hacky. Asked for some attention on that PR.

### CODE REVIEW

**Comment by jryberg** [comment]
Was this never merged? Is it because it's not needed or something else? 

// Johan

**Comment by carlpett** [comment]
Hi @jryberg,
This seems to have fallen of the radar a bit. I was hoping for the linked PR in fsnotify to be merged so this one would not be needed (it essentially "fakes" the merge, so we'd diverge from upstream).
However, that PR doesn't have much activity... Are you affected by #5?

**Comment by jryberg** [comment]
Yes, I'm affected. We have seen strange behaviour where it stops to read logs when the file is rotated in scenarios where two dockers share same file system and one of them rotates the log and the other are streaming the log.

**Comment by jryberg** [comment]
I have merged it in my own fork, just need to figure out how to build it =)

**Comment by carlpett** [comment]
Well, since the upstream merge doesn't seem to be happening, guess we'll merge it here, then.

**Comment by jryberg** [comment]
Thank you =)

Would you please include binaries as well?

**Comment by jryberg** [comment]
I managed to build it using go 1.12.5 and info from your Dockerfile. 

However, one thing that puzzled me was I could not use the source code from the release. I had to use go get from github instead of the tar.gz.

I hope this can help someone =)

```docker
FROM golang:1.12 AS build

RUN go version && \
    go get -v -u github.com/kardianos/govendor && \
    go get -v -u github.com/carlpett/stream_exporter && \
    go install github.com/kardianos/govendor
WORKDIR /go/src/github.com/carlpett/stream_exporter
RUN govendor build +p
````

**Comment by carlpett** [comment]
Hm, I made a release (v0.2.2) which should have built binaries as well. Looks like one of the build tools (`promu`) has broken backwards compatibility.
I'm out travelling at the moment, but will try to fix it and make a "real" release.

**Comment by carlpett** [comment]
@jryberg Release now works!

**Comment by jryberg** [comment]
Thank you.

I can also confirm that we had no hiccups with the latest version. Rotated
logs works just fine now.

**Pull request merged**
